// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shwfzxpypygdxoqxutae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNod2Z6eHB5cHlnZHhvcXh1dGFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MTczMDUsImV4cCI6MjA3NDI5MzMwNX0.aP89797x8EozE1ovZLYEK8shbx02K7xtuH3Cd7jV_Bs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});